language: node_js
node_js:
  - "8.4"
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run build
  - npm run coveralls
branch:
  only:
    - master
    - devel
    - unstable
notifications:
  slack: dreamrich:cTexLtv9sRIcw118O7Q4WejK 
