const actionTypes = {
  APP: {
    SWITCHNAVDRAWER: 'app/drawer_toggle',
    MENUTOGGLE: 'app/menu_toggle',
  },
  MENU: {
    TOGGLEMENU: 'menu/toggle_side_menu',
    REQUESTCHANGE: 'menu/change_side_menu',
  },
  LOGIN: {
    POST: 'login/post',
    FAIL: 'login/fail',
    SUCCESS: 'login/success',
  },
  LOGOUT: 'logout',
  PASSWORD: {
    CHANGE: 'password/change',
    SUCCESS: 'password/success',
    FAIL: 'password/fail',
    RESET: 'password/reset',
    SNACKCLOSE: 'password/snack',
    UNMOUNT: 'password/unmount'
  },
  CLIENT: {
    SUBMIT: 'client/can_submit_form',
    POSTMULTIFORM: 'client/create_multiline_form',
    POSTMULTIFORMSUCCESS: 'client/create_multiline_form_success',
    ADDRESSTYPE: 'client/address_types',
    DATAFORM: 'client/form_initial_data',
    COUNTRIES: 'client/countries',
    STATES: 'client/states',
    STATESUCCESS: 'client/states_success',
    POSTFORM: 'client/create_active',
    POSTFORMSUCCESS: 'client/create_active_success',
    GETFORMSUCCESS: 'client/get_active_success',
    SUBFORM: 'client/create_subforms',
    ADDDEPENDENT: 'client/add_dependent',
    REMOVEDEPENDENT: 'client/remove_dependent',
    ID: 'client/get_client_data',
    ADDRESSTEXT: 'client/change_address_type_text',
  },
  REFRESH_LOGIN: 'refresh_token',
  REGULARCOST: {
    ADD: 'fixed_cost/add',
    REMOVE: 'fixed_cost/remove',
    MANAGER: 'fixed_cost/submit_form',
    SUCCESS: 'fixed_cost/form_success',
    TYPE: 'fixed_cost/types',
    TYPESUCCESS: 'fixed_cost/types_success',
    SUBFORM: 'fixed_cost/create_subforms',
  },
  GOAL:{
    ADD: 'goal/add',
    REMOVE: 'goal/remove',
    MANAGER: 'goal/submit_form',
    SUCCESS: 'goal/form_success',
    TYPE: 'goal/types',
    TYPESUCCESS: 'goal/types_success',
    HASEND: 'goal/form_toggle',
    SUBFORM: 'goal/create_subforms',
  },
  PATRIMONY: {
    FORM: 'patrimony/create_form',
    SUBFORM: 'patrimony/create_subforms',
    SUCCESS: 'patrimony/success',
  },
  ACTIVE: {
    TYPE: 'active/types',
    TYPESUCCESS: 'active/types_success',
    FORM: 'active/create_form',
    SUCCESS: 'active/manager_success_form',
    MANAGER: 'active/create_manager',
    GETMANAGER: 'active/obtain_manager',
    DELETEPROFIT: 'active/remove_active',
    ADD: 'active/add_active_list',
    REMOVE: 'active/remove_active_list',
  },
};

export default actionTypes;
